### ISSUE TITLE
add OPNsense

### ISSUE THREAD

**Issue by fichtner** [FabioLolix/BSD-Timeline#3]
**Adding a distro**

* Distro name: OPNsense

* Base distro: FreeBSD (forked from pfSense; with HardenedBSD additions, migration to HardenedBSD planned)

* Start date: 02.01.2015

* URL: https://opnsense.org/

* (optional) Color in hex: #EC7831

* (optional) Release version: 17.7

If you need more info let me know :)

**Comment by FabioLolix** [comment]
Initial addition made https://github.com/FabioLolix/BSD-Timeline/commit/60b119b87565a1b738de8e1497dcf1a3060fabd7 I still have to add more things
