### ISSUE TITLE
add FuryBSD

### ISSUE THREAD

**Issue by ucSec** [FabioLolix/BSD-Timeline#6]
**Template for adding/discontinuing a distro, all non optional fields are mandatory**

*NOTE: If the issue is NOT about adding/discontinuing a distro, delete these out.*

**Adding a distro**

* Distro name:
FuryBSD
* Base distro:
FreeBSD
* Start date:

* URL:
https://www.furybsd.org/
* (optional) Color in hex:
2688BC
* (optional) Description:
FuryBSD is a brand new, open source FreeBSD desktop. FuryBSD pays homage to desktop BSD projects of the past like PC-BSD and TrueOS with its graphical interface and adds additional tools like a live, hybrid USB / DVD image. FuryBSD is completely free to use and distributed under the BSD license.
* (optional) Release version:
12.1

**Comment by mintblow** [comment]
It's already discontinued.

**Comment by FabioLolix** [comment]
[Added blacklisted](https://github.com/FabioLolix/BSD-Timeline/commit/8ec92cc22e206b8acc3eb77e805adb428425ae8c) for an eventual build with short lived distros
