### ISSUE TITLE
TrueOS discontinue

### ISSUE THREAD

**Issue by ucSec** [FabioLolix/BSD-Timeline#9]
**Discontinuing a distro**

* Distro name:
TrueOS
* Stop date:
I don't know...recently
* Statement URL (if any):
[TrueOS Discontinuation](https://www.truenas.com/TrueOS-Discontinuation/)

**Comment by FabioLolix** [comment]
Done with https://github.com/FabioLolix/BSD-Timeline/commit/61a6ea117f3876c37422c2085dccaf41a37d25cd
